# Configuration Settings for f9p device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

load:
  mask: 3103
  device: 4


device: /dev/ttyACM1
frame_id: gnss_link
rate: 5                     # in Hz
nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may
                            # be either 5 Hz (Dual constellation) or
                            # 8 Hz (GPS only)
dynamic_model: portable    # Airborne < 2G, 2D fix not supported (3D only),
                            # Max Alt: 50km
                            # Max Horizontal Velocity: 250 m/s,
                            # Max Vertical Velocity: 100 m/s
# fix_mode: auto
config_on_startup: false
enable_ppp: false           # Not supported by C94-M8P
# dr_limit: 0

uart1:
  baudrate: 460800           # C94-M8P specific
#   in: 32                    # RTCM 3
#   out: 0                    # No UART out for rover

gnss:
  glonass: true             # Supported by C94-M8P
  beidou: true             # Supported by C94-M8P
  galileo: true
  qzss: true               # Supported by C94-M8P

# dgnss_mode: 3               # Fixed mode

# inf:
#   all: true                   # Whether to display all INF messages in console

# TMODE3 Config
tmode3: 0                   # disable
  # reset: false              # True: disables and re-enables survey-in (resets)
#                             # False: Disables survey-in only if TMODE3 is
#                             # disabled
#   min_dur: 300              # 計測する時間[s]です。十分な長さにします。
#   acc_lim: 3.0              # Survey-In Accuracy Limit [m]



# Enable u-blox message publishers
publish:
  all: false
  aid:
    hui: false

  nav:
    posecef: false
    pvt: true
