base_link2traffic_light_camera:
  x: 2.07
  y: 0.0
  z: 1.57
  roll: 0.0
  pitch: -0.3
  yaw: 0.0
base_link2sensor_kit_base_link:
  x: 0.9
  y: 0.0
  z: 2.0
  roll: -0.001
  pitch: 0.015
  yaw: -0.0364
base_link2gnss:
  x: 0.0
  y: 0.0
  z: 1.8
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
