---
- name: Lanelet2 (install dependencies for building packages)
  apt:
    name:
      - libboost-dev
      - libeigen3-dev
      - libgeographic-dev
      - libpugixml-dev
      - libpython-dev
      - libboost-python-dev
      - python-catkin-tools
    state: latest
    update_cache: yes
  become: yes

- name: Lanelet2 (clone Lanelet2 repository catkin workspace)
  become: no
  git:
    repo: https://github.com/fzi-forschungszentrum-informatik/Lanelet2.git
    dest: "{{ AUTOWARE_DIR }}/src/map/lanelet2/"
    version: 1.0.1

- name: Lanelet2 (clone mrt_cmake_modules catkin workspace)
  become: no
  git:
    repo: https://github.com/KIT-MRT/mrt_cmake_modules.git
    dest: "{{ AUTOWARE_DIR }}/src/map/mrt_cmake_modules/"
    version: 1.0.2
