---
- name: osqp (clone repository)
  become: no
  git:
    repo: https://github.com/oxfordcontrol/osqp.git
    dest: "{{ role_path }}/osqp"
    version: release-0.6.0

- name: osqp (make build dir)
  become: no
  file:
    path: "{{ role_path }}/osqp/{{ item }}"
    state: directory
  with_items:
    - build

- name: osqp (cmake)
  become: no
  command: cmake -G "Unix Makefiles" .. chdir={{ role_path }}/osqp/build

- name: osqp (make all and install)
  become: true
  command: cmake --build . --target install
  args:
    chdir: "{{ role_path }}/osqp/build"
